services:
    okto_media.episode_import_listener:
        class: Okto\MediaBundle\Event\EpisodeImportListener
        arguments: [ "@bprs_jobservice" ]
        tags:
            - { name: kernel.event_listener, event: oktolab_media.imported_episode_metadata, method: onEpisodeMetadataImport }

    okto_media.series_import_listener:
        class: Okto\MediaBundle\Event\SeriesImportListener
        arguments: [ "@bprs_jobservice" ]
        tags:
            - { name: kernel.event_listener, event: oktolab_media.imported_series_metadata, method: onSeriesMetadataImport }

    oktothek_tag.type:
        class: Okto\MediaBundle\Form\TagType
        arguments: [ "@okto_media_tag" ]
        tags:
            - { name: form.type, alias: tag }

    okto_media.episode.type:
        class: Okto\MediaBundle\Form\EpisodeType
        arguments:
            - "%oktolab_media.series_class%"
            - "%oktolab_media.episode_class%"
        tags:
            - { name: form.type }

    oktothek_tag.repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments: [ "AppBundle\\Entity\\Tag" ]

    okto_media.user_repo:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments: [ "%okto_media.user_class%" ]

    okto_media_tag:
        class: Okto\MediaBundle\Model\TagService
        arguments: [ "@doctrine.orm.entity_manager", "%okto_media.tag_class%" ]
        public: true

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    # forms
    okto_media.series_user.type:
        class: Okto\MediaBundle\Form\SeriesUserType
        arguments:  [ "@okto_media.user_repo", "%oktolab_media.series_class%" ]
        tags:
            - { name: form.type }

    okto_media.series_tag.type:
        class: Okto\MediaBundle\Form\SeriesTagType
        arguments:  [ "%oktolab_media.series_class%" ]
        tags:
            - { name: form.type }

    okto_media.series_episode.type:
        class: Okto\MediaBundle\Form\SeriesEpisodeType
        arguments: [ "%oktolab_media.episode_class%" ]
        tags:
            - { name: form.type }

    okto_media.series_state.type:
        class: Okto\MediaBundle\Form\SeriesStateType
        arguments: [ "@translator" ]
        tags:
            - { name: form.type }

    okto_media:
        class: Okto\MediaBundle\Model\MediaService
        arguments:
            - "@oktolab_media"
            - "@oktolab_media_helper"
            - "@doctrine.orm.entity_manager"
            - "@bprs_jobservice"
            - "%okto_media.defaut_queue%"
        public: true

    okto_media_reachme.type:
        class: Okto\MediaBundle\Form\ReachmeType
        arguments: [ "@translator" ]
        tags:
            - { name: form.type }
