services:
    okto_media.episode_import_listener:
        class: Okto\MediaBundle\Event\EpisodeImportListener
        arguments: [ "@bprs_jobservice" ]
        tags:
            - { name: kernel.event_listener, event: oktolab_media.imported_episode_metadata, method: onEpisodeMetadataImport }

    okto_media.series_import_listener:
        class: Okto\MediaBundle\Event\SeriesImportListener
        arguments: [ "@bprs_jobservice" ]
        tags:
            - { name: kernel.event_listener, event: oktolab_media.imported_series_metadata, method: onSeriesMetadataImport }

    oktothek_tag.type:
        class: Okto\MediaBundle\Form\TagType
        arguments: [ "@okto_media_tag" ]
        tags:
            - { name: form.type, alias: tag }

    # oktothek_tag_collection.type:
    #     class: AppBundle\Form\TagCollectionType
    #     arguments: [ "@oktothek_tag.repository" ]
    #     tags:
    #         - { name: form.type, alias: tag_collection }

    okto_media.episode.type:
        class: Okto\MediaBundle\Form\EpisodeType
        arguments: [ "%oktolab_media.series_class%", "%oktolab_media.episode_class%"]
        tags:
            - { name: form.type }

    oktothek_tag.repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments: [ "AppBundle\Entity\Tag" ]
        #arguments:  [ "Okto\MediaBundle\Entity\Tag" ]

    okto_media_tag:
        class: Okto\MediaBundle\Model\TagService
        arguments: [ "@doctrine.orm.entity_manager", "%okto_media.tag_class%"]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
