<?php

namespace MediaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends EntityRepository
{
    public function findNewestPlaylists($numberPlaylists)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM MediaBundle:Playlist p WHERE SIZE(p.items) != 0 ORDER BY p.createdAt ASC'
            )
            ->setMaxResults($numberPlaylists)
            ->getResult();
    }

    public function findPlaylistsForSeriesQuery($series)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM MediaBundle:Playlist p WHERE p.series = :series'
            )
            ->setParameter('series', $series->getId());
    }
}
